# Generated by Django 3.0.8 on 2020-07-23 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 0, 29, 53, 222596)),
        ),
    ]
