# Generated by Django 3.0.8 on 2020-07-23 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20200724_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 4, 26, 25, 759070)),
        ),
    ]
