# Generated by Django 3.0.8 on 2020-07-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_auto_20200724_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 4, 27, 11, 483309)),
        ),
    ]
